---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git on ubutu node
    apt:
       name: git
       state: present 


  - name: install tree on ubuntu nodes
    apt: 
       name: tree 
       state: present 
    
  - name: install wget on ubuntu machine
    apt: 
       name: wget
       state: present  