--- 
- hosts: 172.31.4.138 
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: i want to install webserver on ansible node
    apt: 
       name: apache2
       state: present

  - name: i want to copy myindex file into ansible node
    template:
        src:
        dest: /var/www/html/index.html    