--- 
- hosts: 172.31.4.138
  become: yes
  vars:
      myvar1: git
      myvar2: tree  
      myvar3:  wget

      tasks: 
      - name: install tree on my ubuntu node
        apt:
          name: "{{myvar2}}"

      - name: i want to display myvar2
        debug: 
            msg: "{{myvar2}}"


